language: python
python:
  - "3.6"
before_install:
  - sudo apt-get update
  - pip install pycodestyle codecov
  - python setup.py install
before_script:
  - cp src/unittest/assets/cfg/cloudssh.cfg ~/.cloudssh.cfg
  - mkdir ~/.aws
  - openssl aes-256-cbc -K $encrypted_4c4621b9201c_key -iv $encrypted_4c4621b9201c_iv -in src/unittest/assets/aws/credentials.enc -out ~/.aws/credentials -d
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - pytest
  - coverage run --branch --source=. -m unittest discover -bv
  - coverage report -m
after_success:
  - codecov